// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: followers.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const followByID = `-- name: FollowByID :exec
INSERT INTO followers(created_at, user_id, follower_id)
VALUES ($1, $2, $3)
`

type FollowByIDParams struct {
	CreatedAt  pgtype.Timestamp
	UserID     pgtype.UUID
	FollowerID pgtype.UUID
}

func (q *Queries) FollowByID(ctx context.Context, arg FollowByIDParams) error {
	_, err := q.db.Exec(ctx, followByID, arg.CreatedAt, arg.UserID, arg.FollowerID)
	return err
}

const unfollowByID = `-- name: UnfollowByID :exec
DELETE FROM followers WHERE user_id = $1 AND follower_id = $2
`

type UnfollowByIDParams struct {
	UserID     pgtype.UUID
	FollowerID pgtype.UUID
}

func (q *Queries) UnfollowByID(ctx context.Context, arg UnfollowByIDParams) error {
	_, err := q.db.Exec(ctx, unfollowByID, arg.UserID, arg.FollowerID)
	return err
}
