services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    container_name: gophis-redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"

volumes:
  db-data:
