-- +goose Up

CREATE TABLE IF NOT EXISTS comments (
	id UUID PRIMARY KEY,
	post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
	user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	content TEXT NOT NULL
);

-- +goose Down

DROP TABLE IF EXISTS comments;
